#version 450
#include <common.glsl>

// define descriptors
#define DESC_PALETTE 2
#define DESC_TIME 3
#define DESC_ITERATION 5
#define DESC_STRIPE 6
#define DESC_SLOPE 7
#define DESC_COLOR 8

// include descriptors
#include <desc_iteration.glsl>
#include <desc_palette.glsl>
#include <desc_time.glsl>
#include <desc_stripe.glsl>
#include <desc_slope.glsl>
#include <desc_color.glsl>

// include utilities
#include <utils_iteration.glsl>
#include <utils_palette.glsl>
#include <utils_stripe.glsl>
#include <utils_slope.glsl>
#include <utils_color.glsl>


layout (set = 0, binding = 0) buffer Iteration2MapNormalSSBO {
    double iterations[];
} it2map_normal_settings;

layout (set = 0, binding = 1) buffer Iteration2MapZoomedSSBO {
    double iterations[];
} it2map_zoomed_settings;


layout (set = 1, binding = 0) uniform VideoUBO {
    float default_zoom_increment;
    float current_frame;
} video_settings;

layout (set = 4, binding = 0, rgba8) writeonly uniform image2D merged_image_output;

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


double get_iteration_normal(ivec2 iter_coord, ivec2 offset) {
    return it2map_normal_settings.iterations[get_iteration_index(iter_coord, offset)];
}


double get_iteration_zoomed(ivec2 iter_coord, ivec2 offset) {
    return it2map_zoomed_settings.iterations[get_iteration_index(iter_coord, offset)];
}


vec3 get_normal_final_color(ivec2 ntx_i, ivec2 offset, float nsr){
    double n = get_iteration_normal(ntx_i, offset);

    double nld = get_iteration_normal(ntx_i, offset + ivec2(-1, -1));
    double nd = get_iteration_normal(ntx_i, offset + ivec2(0, -1));
    double nrd = get_iteration_normal(ntx_i, offset + ivec2(1, -1));
    double nl = get_iteration_normal(ntx_i, offset + ivec2(-1, 0));
    double nr = get_iteration_normal(ntx_i, offset + ivec2(1, 0));
    double nlu = get_iteration_normal(ntx_i, offset + ivec2(-1, 1));
    double nu = get_iteration_normal(ntx_i, offset + ivec2(0, 1));
    double nru = get_iteration_normal(ntx_i, offset + ivec2(1, 1));
    return color_apply(palette_get_color(n).rgb * stripe_get_multiplier(n) * slope_get_shade(nld, nd, nrd, nl, nr, nlu, nu, nru, ntx_i, 1 / nsr));
}


void main() {

    vec2 center = vec2(iteration_info_settings.extent) / 2.0;
    vec2 coord = vec2(gl_GlobalInvocationID.xy) - center;
    float r = int(max(0, video_settings.current_frame)) - video_settings.current_frame;

    float nsr = pow(video_settings.default_zoom_increment, r + 1);// exp = 0 ~ 1

    vec2 ntx = coord / nsr + center;

    ivec2 ntx_i = ivec2(floor(ntx));
    vec2 nrt = fract(ntx);

    vec3 nc00 = get_normal_final_color(ntx_i, ivec2(0, 0), nsr);
    vec3 nc10 = get_normal_final_color(ntx_i, ivec2(1, 0), nsr);
    vec3 nc01 = get_normal_final_color(ntx_i, ivec2(0, 1), nsr);
    vec3 nc11 = get_normal_final_color(ntx_i, ivec2(1, 1), nsr);

    vec3 nc0 = nc00 - (nc00 - nc10) * nrt.x;
    vec3 nc1 = nc01 - (nc01 - nc11) * nrt.x;
    vec3 nc = nc1 - (nc1 - nc0) * nrt.y;


    float zsr = pow(video_settings.default_zoom_increment, r); // exp = -1 ~ 0
    vec2 ztx = coord / zsr + center;


    if (ztx.x > iteration_info_settings.extent.x - 2 || ztx.y > iteration_info_settings.extent.y - 2 || ztx.x < 1 || ztx.y < 1 || video_settings.current_frame < 1) {
        imageStore(merged_image_output, ivec2(gl_GlobalInvocationID.xy), vec4(nc, 1));
        return;
    }


    vec2 ztx_min = max((coord - vec2(0.5, 0.5)) / zsr + center, vec2(0));
    vec2 ztx_max = min((coord + vec2(0.5, 0.5)) / zsr + center, vec2(iteration_info_settings.extent));
    ivec2 ztx_i_min = ivec2(floor(ztx_min));
    ivec2 ztx_i_max = ivec2(ceil(ztx_max));
    vec3 zc_sum = vec3(0);
    float zw_sum = 0;

    ivec2 ztx_i = ztx_i_min;

    while (ztx_i.y < ztx_i_max.y) {
        ztx_i.x = ztx_i_min.x;

        while (ztx_i.x < ztx_i_max.x) {
            vec2 w = min(min(min(ztx_i + ivec2(1, 1) - ztx_min, ztx_max - ztx_i), ztx_max - ztx_min), vec2(1, 1));
            float weight = w.x * w.y;

            double zld = get_iteration_zoomed(ztx_i, ivec2(-1, -1));
            double zd = get_iteration_zoomed(ztx_i, ivec2(0, -1));
            double zrd = get_iteration_zoomed(ztx_i, ivec2(1, -1));
            double zl = get_iteration_zoomed(ztx_i, ivec2(-1, 0));
            double zr = get_iteration_zoomed(ztx_i, ivec2(1, 0));
            double zlu = get_iteration_zoomed(ztx_i, ivec2(-1, 1));
            double zu = get_iteration_zoomed(ztx_i, ivec2(0, 1));
            double zru = get_iteration_zoomed(ztx_i, ivec2(1, 1));

            double z_temp = get_iteration_zoomed(ztx_i, ivec2(0));
            vec3 zc_temp = palette_get_color(z_temp).rgb * stripe_get_multiplier(z_temp) * slope_get_shade(zld, zd, zrd, zl, zr, zlu, zu, zru, ztx_i, 1 / zsr);
            zc_sum += zc_temp * weight;
            zw_sum += weight;
            ++ztx_i.x;
        }
        ++ztx_i.y;
    }


    vec3 zc = color_apply(zc_sum / float(zw_sum));

    imageStore(merged_image_output, ivec2(gl_GlobalInvocationID.xy), vec4(nc * (-r) + zc * (r + 1), 1));

}