#version 450
#include <common.glsl>

// define descriptors
#define DESC_ITERATION 0
#define DESC_ITERATION_BUFFER_ACCESS writeonly
#define DESC_RENDER_META 1
#define DESC_BATCH_RESULT 2

// include descriptors
#include <desc_iteration.glsl>
#include <desc_render_meta.glsl>
#include <desc_batch_result.glsl>

// include utilities
#include <utils_mpa.glsl>
#include <utils_perturbation.glsl>
#include <utils_complex.glsl>

layout (constant_id = 0) const uint ignore_mpa = 0;

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;



void main() {


    uint px = gl_GlobalInvocationID.x;
    uint py = gl_GlobalInvocationID.y;
    uvec2 pixel = uvec2(px, py);
    uint index = py * iteration_info_settings.extent.x + px;

    if (px >= int(iteration_info_settings.extent.x) || py >= int(iteration_info_settings.extent.y)) return;
    if (batch_data.staging_values[index].iteration == 0) batch_result_data.completed[index] = 0;
    if (batch_result_data.completed[index] != 0) return;

    vec2 dz = batch_data.staging_values[index].dz;
    uvec2 extent = uvec2(iteration_info_settings.extent);
    float bailout2 = render_meta.bailout * render_meta.bailout;

    uint64_t iteration = batch_data.staging_values[index].iteration;
    uint64_t ref_iteration = batch_data.staging_values[index].ref_iteration;
    vec2 dc = offset_conversion(pixel, extent) + render_meta.offset;
    float prev_distance2 = 0;
    float curr_distance2 = batch_data.staging_values[index].distance2;
    uint batch_iteration = 0;
    uint batch_size = batch_info.batch_size;

    while (iteration < render_meta.max_iteration && batch_iteration < batch_size)
    {
        if (ignore_mpa == 0 && mp_table_meta.len != 0) {
            PA pa = lookup(ref_iteration, dz);
            if (pa.skip > 0) {
                dz = apply(pa, dz, dc);
                iteration += pa.skip;
                ref_iteration += pa.skip;
                ++batch_iteration;

                if (iteration >= render_meta.max_iteration) {
                    break;
                }
            }
        }



        if (ref_iteration != render_meta.max_ref_iteration) {
            vec2 oldZ2 = render_meta.orbit[compress(ref_iteration)] * 2;
            vec2 oldPtbz = oldZ2 + dz;

            dz = mul_comp(oldPtbz, dz) + dc;

            ++ref_iteration;
            ++iteration;
            ++batch_iteration;
        }

        vec2 z = render_meta.orbit[compress(ref_iteration)] + dz;
        prev_distance2 = curr_distance2;
        curr_distance2 = norm2(z);

        if (ref_iteration == render_meta.max_ref_iteration || curr_distance2 < norm2(dz)) {
            ref_iteration = 0;
            dz = z;
        }

        if (curr_distance2 > bailout2) {
            float prev_distance = sqrt(prev_distance2);
            float curr_distance = sqrt(curr_distance2);
            iteration_settings.iterations[index] = double(iteration) + get_exterior_double_value_iteration_ratio(prev_distance, curr_distance);
            batch_result_data.completed[index] = 1;
            return;
        }
    }

    if (iteration >= render_meta.max_iteration) {
        iteration_settings.iterations[index] = render_meta.max_iteration;
        batch_result_data.completed[index] = 1;
        return;
    }

    iteration_settings.iterations[index] = iteration;
    batch_data.staging_values[index].dz = dz;
    batch_data.staging_values[index].ref_iteration = ref_iteration;
    batch_data.staging_values[index].iteration = iteration;
    batch_data.staging_values[index].distance2 = curr_distance2;

}